name: update oculus
on:
  workflow_dispatch:
  schedule:
    - cron: '01 07 * * *'
jobs:
  oculus-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install --registry=https://registry.npm.org
      - name: update json and cover
        run: |
          cd scripts
          python get-store-json.py
          python download-cover.py
      - run: npm build
      - name: Commit data
        run: |
          git config --global user.name 'fwindpeak'
          git config --global user.email 'fwindpeak@users.noreply.github.com'
          git add .
          git commit -m "update oculus store data"
          git push
