name: update oculus
on:
  workflow_dispatch:
  schedule:
    - cron: '01 * * * *'
jobs:
  oculus-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update json and cover
        run: |
          cd scripts
          python get-store-json.py
          python download-app-info.py
          python get-rate-json.py
          python fix-all-data.py
          cp -rf ../public/*.json ../dist/
          cp -rf ../public/detail ../dist/
      - name: Commit data
        run: |
          git config --global user.name 'fwindpeak'
          git config --global user.email 'fwindpeak@users.noreply.github.com'
          git add .
          git commit -m "update oculus store data"
          git push
