name: update oculus
on:
  workflow_dispatch:
  schedule:
    - cron: '01 07 * * *'
jobs:
  oculus-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: update json and cover
        run: |
          cd scripts
          python get-store-json.py
          python download-cover.py
      - run: npm build
      - name: Commit data
        run: |
          git config --global user.name 'fwindpeak'
          git config --global user.email 'fwindpeak@users.noreply.github.com'
          git add .
          git commit -m "update oculus store data"
          git push
